spring:
  # Database configuration
  datasource:
    url: jdbc:mysql://localhost:3306/car_service_db1?createDatabaseIfNotExist=true
    username: root
    password: 12345
  jpa:
    show-sql: true
    hibernate.ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: true


  kafka:
    producer:
      bootstrap-servers: localhost:9092
      ## Configure serializer for key
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      ## Configure serializer for value
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer


